# Generated by Django 6.0.5 on 2026-06-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_todo_created_at_todo_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="due_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
