# Generated by Django 6.0.5 on 2026-06-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_todo_due_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="todo",
            name="completed_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
