# Generated by Django 6.0.5 on 2026-06-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_todo_completed_todo_completed_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="completed_on",
        ),
        migrations.AddField(
            model_name="todo",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
